//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyBase {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_TW {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_TW() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KyBase.Resource.zh_TW", typeof(Resource_zh_TW).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 V&amp;T微克股份有限公司 的本地化字符串。
        /// </summary>
        internal static string AssemblyCompany {
            get {
                return ResourceManager.GetString("AssemblyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © V&amp;T微克股份有限公司 2015 的本地化字符串。
        /// </summary>
        internal static string AssemblyCopyright {
            get {
                return ResourceManager.GetString("AssemblyCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 微克服務據點管理端 的本地化字符串。
        /// </summary>
        internal static string AssemblyDescription {
            get {
                return ResourceManager.GetString("AssemblyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確定 的本地化字符串。
        /// </summary>
        internal static string btn_Confirm {
            get {
                return ResourceManager.GetString("btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手動導出 的本地化字符串。
        /// </summary>
        internal static string btn_CRHManual {
            get {
                return ResourceManager.GetString("btn_CRHManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打開文件 的本地化字符串。
        /// </summary>
        internal static string btn_CRHOpenFile {
            get {
                return ResourceManager.GetString("btn_CRHOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登入 的本地化字符串。
        /// </summary>
        internal static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 瀏覽 的本地化字符串。
        /// </summary>
        internal static string btn_Look {
            get {
                return ResourceManager.GetString("btn_Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 選擇文件 的本地化字符串。
        /// </summary>
        internal static string btn_Scan {
            get {
                return ResourceManager.GetString("btn_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 發送綁定服務據點ID：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_1 {
            get {
                return ResourceManager.GetString("buss_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水單編號是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_10 {
            get {
                return ResourceManager.GetString("buss_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATM的ID是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_11 {
            get {
                return ResourceManager.GetString("buss_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鈔箱編號的ID是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_12 {
            get {
                return ResourceManager.GetString("buss_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否為清分中心：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_13 {
            get {
                return ResourceManager.GetString("buss_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包號是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_14 {
            get {
                return ResourceManager.GetString("buss_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 綑鈔序號是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_15 {
            get {
                return ResourceManager.GetString("buss_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用戶已關閉瀏覽器,用戶選擇的端點設備ID是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_16 {
            get {
                return ResourceManager.GetString("buss_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您綁定的端點設備ID是：{0} 已被IP地址是：{1} 绑定了,一分鐘後將嘗試重新連接！ 的本地化字符串。
        /// </summary>
        internal static string buss_17 {
            get {
                return ResourceManager.GetString("buss_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 嘗試重新連接，已等待 {0} 次。 的本地化字符串。
        /// </summary>
        internal static string buss_18 {
            get {
                return ResourceManager.GetString("buss_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已斷開到推送服務的連接！ 的本地化字符串。
        /// </summary>
        internal static string buss_19 {
            get {
                return ResourceManager.GetString("buss_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到開始命令，端點設備ID是：{0} ，業務類型是：{1}，用户ID是：{2} 的本地化字符串。
        /// </summary>
        internal static string buss_2 {
            get {
                return ResourceManager.GetString("buss_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 該客户端未绑定服務據點，请先綁定服務據點！ 的本地化字符串。
        /// </summary>
        internal static string buss_20 {
            get {
                return ResourceManager.GetString("buss_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服務器異常！ 的本地化字符串。
        /// </summary>
        internal static string buss_21 {
            get {
                return ResourceManager.GetString("buss_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到文件第一個鈔劵號碼時間是 {0} 的本地化字符串。
        /// </summary>
        internal static string buss_22 {
            get {
                return ResourceManager.GetString("buss_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端點設備 {0} 正在進行交易控制！ 的本地化字符串。
        /// </summary>
        internal static string buss_23 {
            get {
                return ResourceManager.GetString("buss_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 業務開始,端點設備ip是 {1} 的本地化字符串。
        /// </summary>
        internal static string buss_24 {
            get {
                return ResourceManager.GetString("buss_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 業務結束,端點設備ip是 {1} 的本地化字符串。
        /// </summary>
        internal static string buss_25 {
            get {
                return ResourceManager.GetString("buss_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跨行調款中臨時路徑 {0} 不存在！ 的本地化字符串。
        /// </summary>
        internal static string buss_26 {
            get {
                return ResourceManager.GetString("buss_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 發送端點設備id是{0}，總金額是{1}，可疑鈔張數是{2}，真鈔張數是{3}，首張鈔劵票號是{4}，末張鈔劵票號是{5}，捆鈔序號是{6} 的本地化字符串。
        /// </summary>
        internal static string buss_27 {
            get {
                return ResourceManager.GetString("buss_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 機器上次連接時間：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_3 {
            get {
                return ResourceManager.GetString("buss_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一批張數是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_4 {
            get {
                return ResourceManager.GetString("buss_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析業務類型為：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_5 {
            get {
                return ResourceManager.GetString("buss_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端點設備ID是：{0} 已失去連接。 的本地化字符串。
        /// </summary>
        internal static string buss_6 {
            get {
                return ResourceManager.GetString("buss_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 機器上次連接時間： {0} 大于當前時間5分鐘，視為未連接。 的本地化字符串。
        /// </summary>
        internal static string buss_7 {
            get {
                return ResourceManager.GetString("buss_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到结束命令,端點設備ID是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_8 {
            get {
                return ResourceManager.GetString("buss_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到撤銷命令 的本地化字符串。
        /// </summary>
        internal static string buss_9 {
            get {
                return ResourceManager.GetString("buss_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 啟用自動導出 的本地化字符串。
        /// </summary>
        internal static string chk_CRHExport {
            get {
                return ResourceManager.GetString("chk_CRHExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 將指定文件夾下的FSN文件導入系统 的本地化字符串。
        /// </summary>
        internal static string chk_FactoryAccess {
            get {
                return ResourceManager.GetString("chk_FactoryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 號碼記錄,櫃台取款,櫃台存款,ATM配钞,ATM清钞 的本地化字符串。
        /// </summary>
        internal static string cmb_BusinessType {
            get {
                return ResourceManager.GetString("cmb_BusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現金收入 的本地化字符串。
        /// </summary>
        internal static string CRH_1 {
            get {
                return ResourceManager.GetString("CRH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATM取款機 的本地化字符串。
        /// </summary>
        internal static string CRH_10 {
            get {
                return ResourceManager.GetString("CRH_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兌換端點設備 的本地化字符串。
        /// </summary>
        internal static string CRH_11 {
            get {
                return ResourceManager.GetString("CRH_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他幣種 的本地化字符串。
        /// </summary>
        internal static string CRH_12 {
            get {
                return ResourceManager.GetString("CRH_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法識別 的本地化字符串。
        /// </summary>
        internal static string CRH_13 {
            get {
                return ResourceManager.GetString("CRH_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現金付出 的本地化字符串。
        /// </summary>
        internal static string CRH_2 {
            get {
                return ResourceManager.GetString("CRH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清分業務 的本地化字符串。
        /// </summary>
        internal static string CRH_3 {
            get {
                return ResourceManager.GetString("CRH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未定義 的本地化字符串。
        /// </summary>
        internal static string CRH_4 {
            get {
                return ResourceManager.GetString("CRH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string CRH_5 {
            get {
                return ResourceManager.GetString("CRH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string CRH_6 {
            get {
                return ResourceManager.GetString("CRH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清分端點設備 的本地化字符串。
        /// </summary>
        internal static string CRH_7 {
            get {
                return ResourceManager.GetString("CRH_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存取款一體機 的本地化字符串。
        /// </summary>
        internal static string CRH_8 {
            get {
                return ResourceManager.GetString("CRH_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 點鈔機 的本地化字符串。
        /// </summary>
        internal static string CRH_9 {
            get {
                return ResourceManager.GetString("CRH_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紀錄日期 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_0 {
            get {
                return ResourceManager.GetString("CRHCommon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 發送銀行編碼 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_1 {
            get {
                return ResourceManager.GetString("CRHCommon_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 業務關聯訊息 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_10 {
            get {
                return ResourceManager.GetString("CRHCommon_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 產生服務據點編碼 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_2 {
            get {
                return ResourceManager.GetString("CRHCommon_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 業務類型 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_3 {
            get {
                return ResourceManager.GetString("CRHCommon_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紀錄數 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_4 {
            get {
                return ResourceManager.GetString("CRHCommon_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現金清分中心 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_5 {
            get {
                return ResourceManager.GetString("CRHCommon_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件版本 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_6 {
            get {
                return ResourceManager.GetString("CRHCommon_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設備類別 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_7 {
            get {
                return ResourceManager.GetString("CRHCommon_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 機型 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_8 {
            get {
                return ResourceManager.GetString("CRHCommon_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設備編號 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_9 {
            get {
                return ResourceManager.GetString("CRHCommon_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導出CRH開始。 的本地化字符串。
        /// </summary>
        internal static string CRHLog_1 {
            get {
                return ResourceManager.GetString("CRHLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法找到ID為 {0} 的非協議端點設備！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_10 {
            get {
                return ResourceManager.GetString("CRHLog_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端點設備ID為 {0} 的機型編號為空！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_11 {
            get {
                return ResourceManager.GetString("CRHLog_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法找到ID為 {0} 的服務據點！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_12 {
            get {
                return ResourceManager.GetString("CRHLog_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法找到ID為 {0} 的服務據點所屬的銀行！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_13 {
            get {
                return ResourceManager.GetString("CRHLog_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 總共 {0} 個批次需要導出CRH文件。 的本地化字符串。
        /// </summary>
        internal static string CRHLog_2 {
            get {
                return ResourceManager.GetString("CRHLog_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建立臨時目錄 {0} 的本地化字符串。
        /// </summary>
        internal static string CRHLog_3 {
            get {
                return ResourceManager.GetString("CRHLog_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建立新CRH文件 {0} 的本地化字符串。
        /// </summary>
        internal static string CRHLog_4 {
            get {
                return ResourceManager.GetString("CRHLog_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成CRH壓所包 {0} 的本地化字符串。
        /// </summary>
        internal static string CRHLog_5 {
            get {
                return ResourceManager.GetString("CRHLog_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 銀行編碼是 {0} 的本地化字符串。
        /// </summary>
        internal static string CRHLog_6 {
            get {
                return ResourceManager.GetString("CRHLog_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法找到批次訊息！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_7 {
            get {
                return ResourceManager.GetString("CRHLog_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次ID為 {0} 服務據點ID為 {1} 端點設備ID為 {2} 轉CRH發生異常！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_8 {
            get {
                return ResourceManager.GetString("CRHLog_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法找到ID為 {0} 的端點設備！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_9 {
            get {
                return ResourceManager.GetString("CRHLog_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_number {
            get {
                return ResourceManager.GetString("CRHRecord_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鈔券票號 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordsign {
            get {
                return ResourceManager.GetString("CRHRecord_recordsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 記錄時間 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordtime {
            get {
                return ResourceManager.GetString("CRHRecord_recordtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 面額 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordvalue {
            get {
                return ResourceManager.GetString("CRHRecord_recordvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版别 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordversion {
            get {
                return ResourceManager.GetString("CRHRecord_recordversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH查看 的本地化字符串。
        /// </summary>
        internal static string CRHReview {
            get {
                return ResourceManager.GetString("CRHReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鈔劵票號文件*.FSN|*.FSN 的本地化字符串。
        /// </summary>
        internal static string Filter_1 {
            get {
                return ResourceManager.GetString("Filter_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GZH壓縮文件*.ZIP|*.ZIP 的本地化字符串。
        /// </summary>
        internal static string Filter_2 {
            get {
                return ResourceManager.GetString("Filter_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH文件|*.CRH 的本地化字符串。
        /// </summary>
        internal static string Filter_3 {
            get {
                return ResourceManager.GetString("Filter_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 擴展名不是FSN或者fsn，移入ErrFiles文件夾 的本地化字符串。
        /// </summary>
        internal static string FSNLog_1 {
            get {
                return ResourceManager.GetString("FSNLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 文件格式不正確！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_2 {
            get {
                return ResourceManager.GetString("FSNLog_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的文件版本不正確！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_3 {
            get {
                return ResourceManager.GetString("FSNLog_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 中的廠商簡稱不存在！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_4 {
            get {
                return ResourceManager.GetString("FSNLog_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 中的服務據點編號不存在！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_5 {
            get {
                return ResourceManager.GetString("FSNLog_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的設備類別不存在！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_6 {
            get {
                return ResourceManager.GetString("FSNLog_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSN文件導入異常！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_7 {
            get {
                return ResourceManager.GetString("FSNLog_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 綁定服務據點 的本地化字符串。
        /// </summary>
        internal static string gb_BindNode {
            get {
                return ResourceManager.GetString("gb_BindNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能設置 的本地化字符串。
        /// </summary>
        internal static string gb_CRH1 {
            get {
                return ResourceManager.GetString("gb_CRH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 數據時間範圍設置 的本地化字符串。
        /// </summary>
        internal static string gb_CRH2 {
            get {
                return ResourceManager.GetString("gb_CRH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動導出路徑設置 的本地化字符串。
        /// </summary>
        internal static string gb_CRH3 {
            get {
                return ResourceManager.GetString("gb_CRH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 的本地化字符串。
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設備IP 的本地化字符串。
        /// </summary>
        internal static string kIpAddress {
            get {
                return ResourceManager.GetString("kIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 狀態 的本地化字符串。
        /// </summary>
        internal static string kStatus {
            get {
                return ResourceManager.GetString("kStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近上傳時間 的本地化字符串。
        /// </summary>
        internal static string kUpdateTime {
            get {
                return ResourceManager.GetString("kUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATM編號 的本地化字符串。
        /// </summary>
        internal static string lab_ATM {
            get {
                return ResourceManager.GetString("lab_ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 業務流水號 的本地化字符串。
        /// </summary>
        internal static string lab_BussinessNumber {
            get {
                return ResourceManager.GetString("lab_BussinessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鈔箱編號 的本地化字符串。
        /// </summary>
        internal static string lab_CashBox {
            get {
                return ResourceManager.GetString("lab_CashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共訊息部分： 的本地化字符串。
        /// </summary>
        internal static string lab_CRHCommon {
            get {
                return ResourceManager.GetString("lab_CRHCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鈔券票號紀錄部分： 的本地化字符串。
        /// </summary>
        internal static string lab_CRHRecord {
            get {
                return ResourceManager.GetString("lab_CRHRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易類型 的本地化字符串。
        /// </summary>
        internal static string lab_DealType {
            get {
                return ResourceManager.GetString("lab_DealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設備服務器IP 的本地化字符串。
        /// </summary>
        internal static string lab_DeviceIp {
            get {
                return ResourceManager.GetString("lab_DeviceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夾： 的本地化字符串。
        /// </summary>
        internal static string lab_Directory {
            get {
                return ResourceManager.GetString("lab_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所屬廠商 的本地化字符串。
        /// </summary>
        internal static string lab_Factory {
            get {
                return ResourceManager.GetString("lab_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本機IP 的本地化字符串。
        /// </summary>
        internal static string lab_LocalIp {
            get {
                return ResourceManager.GetString("lab_LocalIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務據點 的本地化字符串。
        /// </summary>
        internal static string lab_Node {
            get {
                return ResourceManager.GetString("lab_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打開主目錄 的本地化字符串。
        /// </summary>
        internal static string lab_OpenMainDir {
            get {
                return ResourceManager.GetString("lab_OpenMainDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密碼 的本地化字符串。
        /// </summary>
        internal static string lab_Password {
            get {
                return ResourceManager.GetString("lab_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圖像數據庫IP 的本地化字符串。
        /// </summary>
        internal static string lab_PictureIp {
            get {
                return ResourceManager.GetString("lab_PictureIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連接埠 的本地化字符串。
        /// </summary>
        internal static string lab_Port {
            get {
                return ResourceManager.GetString("lab_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服務器IP 的本地化字符串。
        /// </summary>
        internal static string lab_PushIp {
            get {
                return ResourceManager.GetString("lab_PushIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 數據服務器IP 的本地化字符串。
        /// </summary>
        internal static string lab_ServerIp {
            get {
                return ResourceManager.GetString("lab_ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 測試 的本地化字符串。
        /// </summary>
        internal static string lab_Test {
            get {
                return ResourceManager.GetString("lab_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上傳提示： 的本地化字符串。
        /// </summary>
        internal static string lab_UploadTip {
            get {
                return ResourceManager.GetString("lab_UploadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string lab_User {
            get {
                return ResourceManager.GetString("lab_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 軟體版本：1.2.0.0 的本地化字符串。
        /// </summary>
        internal static string lab_Version {
            get {
                return ResourceManager.GetString("lab_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 路徑不存在！ 的本地化字符串。
        /// </summary>
        internal static string log_1 {
            get {
                return ResourceManager.GetString("log_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 異常文本
        /// 的本地化字符串。
        /// </summary>
        internal static string log_10 {
            get {
                return ResourceManager.GetString("log_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呈現時候 的本地化字符串。
        /// </summary>
        internal static string log_11 {
            get {
                return ResourceManager.GetString("log_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 異常類型 的本地化字符串。
        /// </summary>
        internal static string log_12 {
            get {
                return ResourceManager.GetString("log_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 異常訊息 的本地化字符串。
        /// </summary>
        internal static string log_13 {
            get {
                return ResourceManager.GetString("log_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 堆棧調用 的本地化字符串。
        /// </summary>
        internal static string log_14 {
            get {
                return ResourceManager.GetString("log_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 異常辦法 的本地化字符串。
        /// </summary>
        internal static string log_15 {
            get {
                return ResourceManager.GetString("log_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未處理懲罰異常 的本地化字符串。
        /// </summary>
        internal static string log_16 {
            get {
                return ResourceManager.GetString("log_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連接數據服務器異常！ 的本地化字符串。
        /// </summary>
        internal static string log_17 {
            get {
                return ResourceManager.GetString("log_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連接設備服務器異常！ 的本地化字符串。
        /// </summary>
        internal static string log_18 {
            get {
                return ResourceManager.GetString("log_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連接推送服務器異常！ 的本地化字符串。
        /// </summary>
        internal static string log_19 {
            get {
                return ResourceManager.GetString("log_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH導出未啟用！ 的本地化字符串。
        /// </summary>
        internal static string log_2 {
            get {
                return ResourceManager.GetString("log_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連接圖像服務器異常！ 的本地化字符串。
        /// </summary>
        internal static string log_20 {
            get {
                return ResourceManager.GetString("log_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 啟動監聽服務異常！ 的本地化字符串。
        /// </summary>
        internal static string log_21 {
            get {
                return ResourceManager.GetString("log_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 監聽連接異常！ 的本地化字符串。
        /// </summary>
        internal static string log_22 {
            get {
                return ResourceManager.GetString("log_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 啟動接收數據線程異常！ 的本地化字符串。
        /// </summary>
        internal static string log_23 {
            get {
                return ResourceManager.GetString("log_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止服務異常！ 的本地化字符串。
        /// </summary>
        internal static string log_24 {
            get {
                return ResourceManager.GetString("log_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易控制異常！ 的本地化字符串。
        /// </summary>
        internal static string log_25 {
            get {
                return ResourceManager.GetString("log_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日誌輸出異常！ 的本地化字符串。
        /// </summary>
        internal static string log_26 {
            get {
                return ResourceManager.GetString("log_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知錯誤！ 的本地化字符串。
        /// </summary>
        internal static string log_27 {
            get {
                return ResourceManager.GetString("log_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 當前隊列還有{0} 條執行語句...
        ///
        /// 的本地化字符串。
        /// </summary>
        internal static string log_3 {
            get {
                return ResourceManager.GetString("log_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 當前隊列還有{0} 個圖像文件等待上傳... 的本地化字符串。
        /// </summary>
        internal static string log_4 {
            get {
                return ResourceManager.GetString("log_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 圖像文件上傳失敗,將添加到隊列末尾 的本地化字符串。
        /// </summary>
        internal static string log_5 {
            get {
                return ResourceManager.GetString("log_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 網路異常！ 的本地化字符串。
        /// </summary>
        internal static string log_6 {
            get {
                return ResourceManager.GetString("log_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通訊異常！ 的本地化字符串。
        /// </summary>
        internal static string log_7 {
            get {
                return ResourceManager.GetString("log_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端點設備IP地址為 {0} 上次連接時間為 {1} 大於當前5分鐘，將關閉線程！ 的本地化字符串。
        /// </summary>
        internal static string log_8 {
            get {
                return ResourceManager.GetString("log_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 獲取文件中的第一個點鈔時間出錯！ 的本地化字符串。
        /// </summary>
        internal static string log_9 {
            get {
                return ResourceManager.GetString("log_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH查看 的本地化字符串。
        /// </summary>
        internal static string MenuItem_CRHReview {
            get {
                return ResourceManager.GetString("MenuItem_CRHReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能設置 的本地化字符串。
        /// </summary>
        internal static string MenuItem_FunctionSetting {
            get {
                return ResourceManager.GetString("MenuItem_FunctionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 連線狀態 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Log {
            get {
                return ResourceManager.GetString("MenuItem_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登出 的本地化字符串。
        /// </summary>
        internal static string MenuItem_LogOut {
            get {
                return ResourceManager.GetString("MenuItem_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務器設置 的本地化字符串。
        /// </summary>
        internal static string MenuItem_ServerSetting {
            get {
                return ResourceManager.GetString("MenuItem_ServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法連接‘設備服務器’，請查看‘服務器設置’是否正確？ 的本地化字符串。
        /// </summary>
        internal static string msg_1 {
            get {
                return ResourceManager.GetString("msg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出軟體後將無法接收鈔券數據，是否退出軟體？ 的本地化字符串。
        /// </summary>
        internal static string msg_10 {
            get {
                return ResourceManager.GetString("msg_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請選擇文件所屬廠商 的本地化字符串。
        /// </summary>
        internal static string msg_11 {
            get {
                return ResourceManager.GetString("msg_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請選擇所屬服務據點 的本地化字符串。
        /// </summary>
        internal static string msg_12 {
            get {
                return ResourceManager.GetString("msg_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請選擇交易類型 的本地化字符串。
        /// </summary>
        internal static string msg_13 {
            get {
                return ResourceManager.GetString("msg_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請選擇ATM編號和鈔箱編號 的本地化字符串。
        /// </summary>
        internal static string msg_14 {
            get {
                return ResourceManager.GetString("msg_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請填寫水單編號 的本地化字符串。
        /// </summary>
        internal static string msg_15 {
            get {
                return ResourceManager.GetString("msg_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打開日誌窗體異常！ 的本地化字符串。
        /// </summary>
        internal static string msg_16 {
            get {
                return ResourceManager.GetString("msg_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他廠商接入文件夾路徑不存在！ 的本地化字符串。
        /// </summary>
        internal static string msg_17 {
            get {
                return ResourceManager.GetString("msg_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH導出路徑不存在！ 的本地化字符串。
        /// </summary>
        internal static string msg_18 {
            get {
                return ResourceManager.GetString("msg_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導出成功！是否打開導出目錄？ 的本地化字符串。
        /// </summary>
        internal static string msg_19 {
            get {
                return ResourceManager.GetString("msg_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 啟動監聽異常！ 的本地化字符串。
        /// </summary>
        internal static string msg_2 {
            get {
                return ResourceManager.GetString("msg_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒後將自動關閉 的本地化字符串。
        /// </summary>
        internal static string msg_20 {
            get {
                return ResourceManager.GetString("msg_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 請設置端口號 的本地化字符串。
        /// </summary>
        internal static string msg_21 {
            get {
                return ResourceManager.GetString("msg_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服務器連接成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_22 {
            get {
                return ResourceManager.GetString("msg_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服務器連接失敗！ 的本地化字符串。
        /// </summary>
        internal static string msg_23 {
            get {
                return ResourceManager.GetString("msg_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圖像服務器連接成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_24 {
            get {
                return ResourceManager.GetString("msg_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圖像服務器連接失敗！ 的本地化字符串。
        /// </summary>
        internal static string msg_25 {
            get {
                return ResourceManager.GetString("msg_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設備服務器連接成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_26 {
            get {
                return ResourceManager.GetString("msg_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設備服務器連接失敗！ 的本地化字符串。
        /// </summary>
        internal static string msg_27 {
            get {
                return ResourceManager.GetString("msg_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 數據服務器連接成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_28 {
            get {
                return ResourceManager.GetString("msg_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 數據服務器連接失敗！ 的本地化字符串。
        /// </summary>
        internal static string msg_29 {
            get {
                return ResourceManager.GetString("msg_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法連接‘推送服務器’，請查看‘服務器設置’是否正確？ 的本地化字符串。
        /// </summary>
        internal static string msg_3 {
            get {
                return ResourceManager.GetString("msg_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 綁定成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_30 {
            get {
                return ResourceManager.GetString("msg_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 綁定失敗！ 的本地化字符串。
        /// </summary>
        internal static string msg_31 {
            get {
                return ResourceManager.GetString("msg_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 已經綁定了IP：{1} 的本地化字符串。
        /// </summary>
        internal static string msg_32 {
            get {
                return ResourceManager.GetString("msg_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否繼續？ 的本地化字符串。
        /// </summary>
        internal static string msg_33 {
            get {
                return ResourceManager.GetString("msg_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法連接‘數據服務器’，請查看‘服務器設置’是否正確？ 的本地化字符串。
        /// </summary>
        internal static string msg_4 {
            get {
                return ResourceManager.GetString("msg_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法連接&apos;‘圖像數據庫’，請查看‘服務器設置’是否正確？ 的本地化字符串。
        /// </summary>
        internal static string msg_5 {
            get {
                return ResourceManager.GetString("msg_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服務器還未配置，請在選單下選擇‘服務器設置進行配置！ 的本地化字符串。
        /// </summary>
        internal static string msg_6 {
            get {
                return ResourceManager.GetString("msg_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密碼錯誤,請重新輸入！ 的本地化字符串。
        /// </summary>
        internal static string msg_7 {
            get {
                return ResourceManager.GetString("msg_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在！ 的本地化字符串。
        /// </summary>
        internal static string msg_8 {
            get {
                return ResourceManager.GetString("msg_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 無法連接設備數據庫！ 的本地化字符串。
        /// </summary>
        internal static string msg_9 {
            get {
                return ResourceManager.GetString("msg_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string msg_Tip {
            get {
                return ResourceManager.GetString("msg_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string msg_Warn {
            get {
                return ResourceManager.GetString("msg_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSN文件 的本地化字符串。
        /// </summary>
        internal static string rad_FSN {
            get {
                return ResourceManager.GetString("rad_FSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GZH文件 的本地化字符串。
        /// </summary>
        internal static string rad_GZH {
            get {
                return ResourceManager.GetString("rad_GZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        internal static string rb_CRHToday {
            get {
                return ResourceManager.GetString("rb_CRHToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昨天 的本地化字符串。
        /// </summary>
        internal static string rb_CRHYesterday {
            get {
                return ResourceManager.GetString("rb_CRHYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導入失敗！ 的本地化字符串。
        /// </summary>
        internal static string str_ImportFail {
            get {
                return ResourceManager.GetString("str_ImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 導入成功！ 的本地化字符串。
        /// </summary>
        internal static string str_ImportSuccess {
            get {
                return ResourceManager.GetString("str_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 業務日誌 的本地化字符串。
        /// </summary>
        internal static string tab_Bussiness {
            get {
                return ResourceManager.GetString("tab_Bussiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令日誌 的本地化字符串。
        /// </summary>
        internal static string tab_Cmd {
            get {
                return ResourceManager.GetString("tab_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH導出 的本地化字符串。
        /// </summary>
        internal static string tab_CRHExport {
            get {
                return ResourceManager.GetString("tab_CRHExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 設備監控 的本地化字符串。
        /// </summary>
        internal static string tab_DeviceControl {
            get {
                return ResourceManager.GetString("tab_DeviceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件上傳 的本地化字符串。
        /// </summary>
        internal static string tab_FileUpload {
            get {
                return ResourceManager.GetString("tab_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSN導入日誌 的本地化字符串。
        /// </summary>
        internal static string tab_FsnImport {
            get {
                return ResourceManager.GetString("tab_FsnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 廠商連接 的本地化字符串。
        /// </summary>
        internal static string tab_OtherFactoryAccess {
            get {
                return ResourceManager.GetString("tab_OtherFactoryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登錄 的本地化字符串。
        /// </summary>
        internal static string tab_UserLogin {
            get {
                return ResourceManager.GetString("tab_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 異步接收命令異常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_1 {
            get {
                return ResourceManager.GetString("TCPLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，傳輸數據結束命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_10 {
            get {
                return ResourceManager.GetString("TCPLog_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，時間同步命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_11 {
            get {
                return ResourceManager.GetString("TCPLog_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，心跳命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_12 {
            get {
                return ResourceManager.GetString("TCPLog_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，文件大小 {1} 字節,文件大小超過5M,將關閉連接！ {2} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_13 {
            get {
                return ResourceManager.GetString("TCPLog_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 達到最大連接數30的限制！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_14 {
            get {
                return ResourceManager.GetString("TCPLog_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，一次請求文件數超過30個，將關閉連接！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_15 {
            get {
                return ResourceManager.GetString("TCPLog_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}關閉線程！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_16 {
            get {
                return ResourceManager.GetString("TCPLog_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紀錄Amount日誌異常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_17 {
            get {
                return ResourceManager.GetString("TCPLog_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紀錄命令日誌異常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_18 {
            get {
                return ResourceManager.GetString("TCPLog_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紀錄業務日誌異常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_19 {
            get {
                return ResourceManager.GetString("TCPLog_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 異步發送命令異常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_2 {
            get {
                return ResourceManager.GetString("TCPLog_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 紀錄FSN日誌異常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_20 {
            get {
                return ResourceManager.GetString("TCPLog_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令長度 {0} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_3 {
            get {
                return ResourceManager.GetString("TCPLog_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新連接 {0} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_4 {
            get {
                return ResourceManager.GetString("TCPLog_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}  IP地址未知,請確認以添加IP地址，再重啟客戶端或等待5分鐘自動更新！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_5 {
            get {
                return ResourceManager.GetString("TCPLog_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 連接已存在！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_6 {
            get {
                return ResourceManager.GetString("TCPLog_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 未知命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_7 {
            get {
                return ResourceManager.GetString("TCPLog_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，傳輸數據請求命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_8 {
            get {
                return ResourceManager.GetString("TCPLog_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，鈔劵訊息發送命令 數據包長度  {1}  鈔劵張數 {2} {3} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_9 {
            get {
                return ResourceManager.GetString("TCPLog_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 當前總共 {0} 調收數據線程！ 的本地化字符串。
        /// </summary>
        internal static string TestLog_1 {
            get {
                return ResourceManager.GetString("TestLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在導出CRH... 的本地化字符串。
        /// </summary>
        internal static string wf_CRHExport {
            get {
                return ResourceManager.GetString("wf_CRHExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在初始化... 的本地化字符串。
        /// </summary>
        internal static string wf_Init {
            get {
                return ResourceManager.GetString("wf_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在載入數據... 的本地化字符串。
        /// </summary>
        internal static string wf_LoadData {
            get {
                return ResourceManager.GetString("wf_LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在登錄... 的本地化字符串。
        /// </summary>
        internal static string wf_Login {
            get {
                return ResourceManager.GetString("wf_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存文件... 的本地化字符串。
        /// </summary>
        internal static string wf_SaveFile {
            get {
                return ResourceManager.GetString("wf_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在啟動監聽... 的本地化字符串。
        /// </summary>
        internal static string wf_StartListen {
            get {
                return ResourceManager.GetString("wf_StartListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在啟動推送... 的本地化字符串。
        /// </summary>
        internal static string wf_StartPush {
            get {
                return ResourceManager.GetString("wf_StartPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止監聽... 的本地化字符串。
        /// </summary>
        internal static string wf_StopListen {
            get {
                return ResourceManager.GetString("wf_StopListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止推送... 的本地化字符串。
        /// </summary>
        internal static string wf_StopPush {
            get {
                return ResourceManager.GetString("wf_StopPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在測試設備服務器... 的本地化字符串。
        /// </summary>
        internal static string wf_TestDevice {
            get {
                return ResourceManager.GetString("wf_TestDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在測試圖像服務器... 的本地化字符串。
        /// </summary>
        internal static string wf_TestPicture {
            get {
                return ResourceManager.GetString("wf_TestPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在測試推送服務器... 的本地化字符串。
        /// </summary>
        internal static string wf_TestPush {
            get {
                return ResourceManager.GetString("wf_TestPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在測試數據服務器... 的本地化字符串。
        /// </summary>
        internal static string wf_TestServer {
            get {
                return ResourceManager.GetString("wf_TestServer", resourceCulture);
            }
        }
    }
}
