//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KyBase {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KyBase.Resource.zh_CN", typeof(Resource_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 广州康艺电子有限公司 的本地化字符串。
        /// </summary>
        internal static string AssemblyCompany {
            get {
                return ResourceManager.GetString("AssemblyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 广州康艺电子有限公司 2015 的本地化字符串。
        /// </summary>
        internal static string AssemblyCopyright {
            get {
                return ResourceManager.GetString("AssemblyCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 康艺网点管理端 的本地化字符串。
        /// </summary>
        internal static string AssemblyDescription {
            get {
                return ResourceManager.GetString("AssemblyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string btn_Confirm {
            get {
                return ResourceManager.GetString("btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动导出 的本地化字符串。
        /// </summary>
        internal static string btn_CRHManual {
            get {
                return ResourceManager.GetString("btn_CRHManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 的本地化字符串。
        /// </summary>
        internal static string btn_CRHOpenFile {
            get {
                return ResourceManager.GetString("btn_CRHOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        internal static string btn_Look {
            get {
                return ResourceManager.GetString("btn_Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件 的本地化字符串。
        /// </summary>
        internal static string btn_Scan {
            get {
                return ResourceManager.GetString("btn_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送绑定网点id：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_1 {
            get {
                return ResourceManager.GetString("buss_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务流水号是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_10 {
            get {
                return ResourceManager.GetString("buss_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATM的id是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_11 {
            get {
                return ResourceManager.GetString("buss_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钞箱编号的id是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_12 {
            get {
                return ResourceManager.GetString("buss_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否为清分中心：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_13 {
            get {
                return ResourceManager.GetString("buss_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包号是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_14 {
            get {
                return ResourceManager.GetString("buss_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捆钞序号是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_15 {
            get {
                return ResourceManager.GetString("buss_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已关闭浏览器,用户选择的机具id是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_16 {
            get {
                return ResourceManager.GetString("buss_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您绑定的网点id是：{0} 已被IP地址是：{1} 绑定了,一分钟后将尝试重连！ 的本地化字符串。
        /// </summary>
        internal static string buss_17 {
            get {
                return ResourceManager.GetString("buss_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试重连，已等待 {0} 次。 的本地化字符串。
        /// </summary>
        internal static string buss_18 {
            get {
                return ResourceManager.GetString("buss_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已断开到推送服务的连接！ 的本地化字符串。
        /// </summary>
        internal static string buss_19 {
            get {
                return ResourceManager.GetString("buss_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到开始命令，机具id是：{0} ，业务类型是：{1}，用户id是：{2} 的本地化字符串。
        /// </summary>
        internal static string buss_2 {
            get {
                return ResourceManager.GetString("buss_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该客户端未绑定网点，请先绑定网点！ 的本地化字符串。
        /// </summary>
        internal static string buss_20 {
            get {
                return ResourceManager.GetString("buss_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服务器异常！ 的本地化字符串。
        /// </summary>
        internal static string buss_21 {
            get {
                return ResourceManager.GetString("buss_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到文件的第一个冠字号码时间是 {0} 的本地化字符串。
        /// </summary>
        internal static string buss_22 {
            get {
                return ResourceManager.GetString("buss_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机具 {0} 正在进行交易控制！ 的本地化字符串。
        /// </summary>
        internal static string buss_23 {
            get {
                return ResourceManager.GetString("buss_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 业务开始,机具ip是 {1} 的本地化字符串。
        /// </summary>
        internal static string buss_24 {
            get {
                return ResourceManager.GetString("buss_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 业务结束,机具ip是 {1} 的本地化字符串。
        /// </summary>
        internal static string buss_25 {
            get {
                return ResourceManager.GetString("buss_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跨行调款中临时路径 {0} 不存在！ 的本地化字符串。
        /// </summary>
        internal static string buss_26 {
            get {
                return ResourceManager.GetString("buss_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送机具id是{0}，总金额是{1}，可疑币张数是{2}，真币张数是{3}，首张冠字号是{4}，末张冠字号是{5}，捆钞序号是{6} 的本地化字符串。
        /// </summary>
        internal static string buss_27 {
            get {
                return ResourceManager.GetString("buss_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器上次连接时间：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_3 {
            get {
                return ResourceManager.GetString("buss_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一批张数是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_4 {
            get {
                return ResourceManager.GetString("buss_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析业务类型为：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_5 {
            get {
                return ResourceManager.GetString("buss_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机具id是：{0} 已失去连接。 的本地化字符串。
        /// </summary>
        internal static string buss_6 {
            get {
                return ResourceManager.GetString("buss_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器上次连接时间： {0} 大于当前时间5分钟，视为未连接。 的本地化字符串。
        /// </summary>
        internal static string buss_7 {
            get {
                return ResourceManager.GetString("buss_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到结束命令,机具id是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_8 {
            get {
                return ResourceManager.GetString("buss_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到撤销命令 的本地化字符串。
        /// </summary>
        internal static string buss_9 {
            get {
                return ResourceManager.GetString("buss_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用自动导出 的本地化字符串。
        /// </summary>
        internal static string chk_CRHExport {
            get {
                return ResourceManager.GetString("chk_CRHExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将指定文件夹下的FSN文件导入系统 的本地化字符串。
        /// </summary>
        internal static string chk_FactoryAccess {
            get {
                return ResourceManager.GetString("chk_FactoryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 号码记录,柜面取款,柜面存款,ATM配钞,ATM清钞 的本地化字符串。
        /// </summary>
        internal static string cmb_BusinessType {
            get {
                return ResourceManager.GetString("cmb_BusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现金收入 的本地化字符串。
        /// </summary>
        internal static string CRH_1 {
            get {
                return ResourceManager.GetString("CRH_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取款机 的本地化字符串。
        /// </summary>
        internal static string CRH_10 {
            get {
                return ResourceManager.GetString("CRH_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 兑换机具 的本地化字符串。
        /// </summary>
        internal static string CRH_11 {
            get {
                return ResourceManager.GetString("CRH_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他币种 的本地化字符串。
        /// </summary>
        internal static string CRH_12 {
            get {
                return ResourceManager.GetString("CRH_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法识别 的本地化字符串。
        /// </summary>
        internal static string CRH_13 {
            get {
                return ResourceManager.GetString("CRH_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现金付出 的本地化字符串。
        /// </summary>
        internal static string CRH_2 {
            get {
                return ResourceManager.GetString("CRH_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清分业务 的本地化字符串。
        /// </summary>
        internal static string CRH_3 {
            get {
                return ResourceManager.GetString("CRH_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未定义 的本地化字符串。
        /// </summary>
        internal static string CRH_4 {
            get {
                return ResourceManager.GetString("CRH_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string CRH_5 {
            get {
                return ResourceManager.GetString("CRH_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string CRH_6 {
            get {
                return ResourceManager.GetString("CRH_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清分机具 的本地化字符串。
        /// </summary>
        internal static string CRH_7 {
            get {
                return ResourceManager.GetString("CRH_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存取款一体机 的本地化字符串。
        /// </summary>
        internal static string CRH_8 {
            get {
                return ResourceManager.GetString("CRH_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点钞机 的本地化字符串。
        /// </summary>
        internal static string CRH_9 {
            get {
                return ResourceManager.GetString("CRH_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录日期 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_0 {
            get {
                return ResourceManager.GetString("CRHCommon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报送银行编码 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_1 {
            get {
                return ResourceManager.GetString("CRHCommon_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务关联信息 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_10 {
            get {
                return ResourceManager.GetString("CRHCommon_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成网点编码 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_2 {
            get {
                return ResourceManager.GetString("CRHCommon_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务类型 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_3 {
            get {
                return ResourceManager.GetString("CRHCommon_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录数 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_4 {
            get {
                return ResourceManager.GetString("CRHCommon_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现金清分中心 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_5 {
            get {
                return ResourceManager.GetString("CRHCommon_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件版本 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_6 {
            get {
                return ResourceManager.GetString("CRHCommon_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类别 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_7 {
            get {
                return ResourceManager.GetString("CRHCommon_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机型 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_8 {
            get {
                return ResourceManager.GetString("CRHCommon_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备编号 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_9 {
            get {
                return ResourceManager.GetString("CRHCommon_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出CRH开始。 的本地化字符串。
        /// </summary>
        internal static string CRHLog_1 {
            get {
                return ResourceManager.GetString("CRHLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到id为 {0} 的非协议机具！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_10 {
            get {
                return ResourceManager.GetString("CRHLog_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机具id为 {0} 的机型编号为空！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_11 {
            get {
                return ResourceManager.GetString("CRHLog_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到id为 {0} 的网点！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_12 {
            get {
                return ResourceManager.GetString("CRHLog_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到id为 {0} 的网点所属的银行！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_13 {
            get {
                return ResourceManager.GetString("CRHLog_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总共 {0} 个批次需要导出CRH文件。 的本地化字符串。
        /// </summary>
        internal static string CRHLog_2 {
            get {
                return ResourceManager.GetString("CRHLog_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建立临时目录 {0} 的本地化字符串。
        /// </summary>
        internal static string CRHLog_3 {
            get {
                return ResourceManager.GetString("CRHLog_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建立新CRH文件 {0} 的本地化字符串。
        /// </summary>
        internal static string CRHLog_4 {
            get {
                return ResourceManager.GetString("CRHLog_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成CRH压缩包 {0} 的本地化字符串。
        /// </summary>
        internal static string CRHLog_5 {
            get {
                return ResourceManager.GetString("CRHLog_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行编码是 {0} 的本地化字符串。
        /// </summary>
        internal static string CRHLog_6 {
            get {
                return ResourceManager.GetString("CRHLog_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到批次信息！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_7 {
            get {
                return ResourceManager.GetString("CRHLog_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次id为 {0} 网点id为 {1} 机具id为 {2} 转CRH发生异常！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_8 {
            get {
                return ResourceManager.GetString("CRHLog_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到id为 {0} 的机具！ 的本地化字符串。
        /// </summary>
        internal static string CRHLog_9 {
            get {
                return ResourceManager.GetString("CRHLog_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_number {
            get {
                return ResourceManager.GetString("CRHRecord_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冠字号码 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordsign {
            get {
                return ResourceManager.GetString("CRHRecord_recordsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录时间 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordtime {
            get {
                return ResourceManager.GetString("CRHRecord_recordtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 币值 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordvalue {
            get {
                return ResourceManager.GetString("CRHRecord_recordvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版别 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordversion {
            get {
                return ResourceManager.GetString("CRHRecord_recordversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH查看 的本地化字符串。
        /// </summary>
        internal static string CRHReview {
            get {
                return ResourceManager.GetString("CRHReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纸币冠字号码文件*.FSN|*.FSN 的本地化字符串。
        /// </summary>
        internal static string Filter_1 {
            get {
                return ResourceManager.GetString("Filter_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GZH压缩文件*.ZIP|*.ZIP 的本地化字符串。
        /// </summary>
        internal static string Filter_2 {
            get {
                return ResourceManager.GetString("Filter_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH文件|*.CRH 的本地化字符串。
        /// </summary>
        internal static string Filter_3 {
            get {
                return ResourceManager.GetString("Filter_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 扩展名不是FSN或者fsn，移入ErrFiles文件夹 的本地化字符串。
        /// </summary>
        internal static string FSNLog_1 {
            get {
                return ResourceManager.GetString("FSNLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 文件格式不正确！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_2 {
            get {
                return ResourceManager.GetString("FSNLog_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的文件版本不正确！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_3 {
            get {
                return ResourceManager.GetString("FSNLog_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 中的厂家简称不存在！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_4 {
            get {
                return ResourceManager.GetString("FSNLog_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 中的网点编号不存在！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_5 {
            get {
                return ResourceManager.GetString("FSNLog_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的设备类别不存在！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_6 {
            get {
                return ResourceManager.GetString("FSNLog_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSN文件导入异常！ 的本地化字符串。
        /// </summary>
        internal static string FSNLog_7 {
            get {
                return ResourceManager.GetString("FSNLog_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定网点 的本地化字符串。
        /// </summary>
        internal static string gb_BindNode {
            get {
                return ResourceManager.GetString("gb_BindNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能设置 的本地化字符串。
        /// </summary>
        internal static string gb_CRH1 {
            get {
                return ResourceManager.GetString("gb_CRH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据时间范围设置 的本地化字符串。
        /// </summary>
        internal static string gb_CRH2 {
            get {
                return ResourceManager.GetString("gb_CRH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动导出路径设置 的本地化字符串。
        /// </summary>
        internal static string gb_CRH3 {
            get {
                return ResourceManager.GetString("gb_CRH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 的本地化字符串。
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备IP 的本地化字符串。
        /// </summary>
        internal static string kIpAddress {
            get {
                return ResourceManager.GetString("kIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string kStatus {
            get {
                return ResourceManager.GetString("kStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近上传时间 的本地化字符串。
        /// </summary>
        internal static string kUpdateTime {
            get {
                return ResourceManager.GetString("kUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATM编号 的本地化字符串。
        /// </summary>
        internal static string lab_ATM {
            get {
                return ResourceManager.GetString("lab_ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务流水号 的本地化字符串。
        /// </summary>
        internal static string lab_BussinessNumber {
            get {
                return ResourceManager.GetString("lab_BussinessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钞箱编号 的本地化字符串。
        /// </summary>
        internal static string lab_CashBox {
            get {
                return ResourceManager.GetString("lab_CashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共信息部分： 的本地化字符串。
        /// </summary>
        internal static string lab_CRHCommon {
            get {
                return ResourceManager.GetString("lab_CRHCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冠字号码记录部分： 的本地化字符串。
        /// </summary>
        internal static string lab_CRHRecord {
            get {
                return ResourceManager.GetString("lab_CRHRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易类型 的本地化字符串。
        /// </summary>
        internal static string lab_DealType {
            get {
                return ResourceManager.GetString("lab_DealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备服务器IP 的本地化字符串。
        /// </summary>
        internal static string lab_DeviceIp {
            get {
                return ResourceManager.GetString("lab_DeviceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹： 的本地化字符串。
        /// </summary>
        internal static string lab_Directory {
            get {
                return ResourceManager.GetString("lab_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属厂家 的本地化字符串。
        /// </summary>
        internal static string lab_Factory {
            get {
                return ResourceManager.GetString("lab_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本机IP 的本地化字符串。
        /// </summary>
        internal static string lab_LocalIp {
            get {
                return ResourceManager.GetString("lab_LocalIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属网点 的本地化字符串。
        /// </summary>
        internal static string lab_Node {
            get {
                return ResourceManager.GetString("lab_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开主目录 的本地化字符串。
        /// </summary>
        internal static string lab_OpenMainDir {
            get {
                return ResourceManager.GetString("lab_OpenMainDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string lab_Password {
            get {
                return ResourceManager.GetString("lab_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像数据库IP 的本地化字符串。
        /// </summary>
        internal static string lab_PictureIp {
            get {
                return ResourceManager.GetString("lab_PictureIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string lab_Port {
            get {
                return ResourceManager.GetString("lab_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服务器IP 的本地化字符串。
        /// </summary>
        internal static string lab_PushIp {
            get {
                return ResourceManager.GetString("lab_PushIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据服务器IP 的本地化字符串。
        /// </summary>
        internal static string lab_ServerIp {
            get {
                return ResourceManager.GetString("lab_ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string lab_Test {
            get {
                return ResourceManager.GetString("lab_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传提示： 的本地化字符串。
        /// </summary>
        internal static string lab_UploadTip {
            get {
                return ResourceManager.GetString("lab_UploadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string lab_User {
            get {
                return ResourceManager.GetString("lab_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本：1.2.0.0 的本地化字符串。
        /// </summary>
        internal static string lab_Version {
            get {
                return ResourceManager.GetString("lab_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 路径不存在！ 的本地化字符串。
        /// </summary>
        internal static string log_1 {
            get {
                return ResourceManager.GetString("log_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常文本 的本地化字符串。
        /// </summary>
        internal static string log_10 {
            get {
                return ResourceManager.GetString("log_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呈现时候 的本地化字符串。
        /// </summary>
        internal static string log_11 {
            get {
                return ResourceManager.GetString("log_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常类型 的本地化字符串。
        /// </summary>
        internal static string log_12 {
            get {
                return ResourceManager.GetString("log_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常信息 的本地化字符串。
        /// </summary>
        internal static string log_13 {
            get {
                return ResourceManager.GetString("log_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 堆栈调用 的本地化字符串。
        /// </summary>
        internal static string log_14 {
            get {
                return ResourceManager.GetString("log_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常办法 的本地化字符串。
        /// </summary>
        internal static string log_15 {
            get {
                return ResourceManager.GetString("log_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未处理惩罚异常 的本地化字符串。
        /// </summary>
        internal static string log_16 {
            get {
                return ResourceManager.GetString("log_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接数据服务器异常！ 的本地化字符串。
        /// </summary>
        internal static string log_17 {
            get {
                return ResourceManager.GetString("log_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接设备服务器异常！ 的本地化字符串。
        /// </summary>
        internal static string log_18 {
            get {
                return ResourceManager.GetString("log_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接推送服务器异常！ 的本地化字符串。
        /// </summary>
        internal static string log_19 {
            get {
                return ResourceManager.GetString("log_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH导出未启用！ 的本地化字符串。
        /// </summary>
        internal static string log_2 {
            get {
                return ResourceManager.GetString("log_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接图像服务器异常！ 的本地化字符串。
        /// </summary>
        internal static string log_20 {
            get {
                return ResourceManager.GetString("log_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动监听服务异常！ 的本地化字符串。
        /// </summary>
        internal static string log_21 {
            get {
                return ResourceManager.GetString("log_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监听连接异常！ 的本地化字符串。
        /// </summary>
        internal static string log_22 {
            get {
                return ResourceManager.GetString("log_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动接收数据线程异常！ 的本地化字符串。
        /// </summary>
        internal static string log_23 {
            get {
                return ResourceManager.GetString("log_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止服务异常！ 的本地化字符串。
        /// </summary>
        internal static string log_24 {
            get {
                return ResourceManager.GetString("log_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易控制异常！ 的本地化字符串。
        /// </summary>
        internal static string log_25 {
            get {
                return ResourceManager.GetString("log_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志输出异常！ 的本地化字符串。
        /// </summary>
        internal static string log_26 {
            get {
                return ResourceManager.GetString("log_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误！ 的本地化字符串。
        /// </summary>
        internal static string log_27 {
            get {
                return ResourceManager.GetString("log_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件长度不符！ 的本地化字符串。
        /// </summary>
        internal static string log_28 {
            get {
                return ResourceManager.GetString("log_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前队列还有{0}条执行语句... 的本地化字符串。
        /// </summary>
        internal static string log_3 {
            get {
                return ResourceManager.GetString("log_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前队列还有{0}个图像文件等待上传... 的本地化字符串。
        /// </summary>
        internal static string log_4 {
            get {
                return ResourceManager.GetString("log_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 图像文件上传失败,将添加到队列末尾 的本地化字符串。
        /// </summary>
        internal static string log_5 {
            get {
                return ResourceManager.GetString("log_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络异常！ 的本地化字符串。
        /// </summary>
        internal static string log_6 {
            get {
                return ResourceManager.GetString("log_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信异常！ 的本地化字符串。
        /// </summary>
        internal static string log_7 {
            get {
                return ResourceManager.GetString("log_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机具IP地址为为 {0} 上次连接时间为 {1} 大于当前5分钟，将关闭线程！ 的本地化字符串。
        /// </summary>
        internal static string log_8 {
            get {
                return ResourceManager.GetString("log_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取文件中的第一个点钞时间出错！ 的本地化字符串。
        /// </summary>
        internal static string log_9 {
            get {
                return ResourceManager.GetString("log_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH查看 的本地化字符串。
        /// </summary>
        internal static string MenuItem_CRHReview {
            get {
                return ResourceManager.GetString("MenuItem_CRHReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能设置 的本地化字符串。
        /// </summary>
        internal static string MenuItem_FunctionSetting {
            get {
                return ResourceManager.GetString("MenuItem_FunctionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Log {
            get {
                return ResourceManager.GetString("MenuItem_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string MenuItem_LogOut {
            get {
                return ResourceManager.GetString("MenuItem_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器设置 的本地化字符串。
        /// </summary>
        internal static string MenuItem_ServerSetting {
            get {
                return ResourceManager.GetString("MenuItem_ServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接‘设备服务器’，请查看‘服务器设置’是否正确？ 的本地化字符串。
        /// </summary>
        internal static string msg_1 {
            get {
                return ResourceManager.GetString("msg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出软件后将无法接收纸币数据，是否退出软件？ 的本地化字符串。
        /// </summary>
        internal static string msg_10 {
            get {
                return ResourceManager.GetString("msg_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件所属厂家 的本地化字符串。
        /// </summary>
        internal static string msg_11 {
            get {
                return ResourceManager.GetString("msg_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择所属网点 的本地化字符串。
        /// </summary>
        internal static string msg_12 {
            get {
                return ResourceManager.GetString("msg_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择交易类型 的本地化字符串。
        /// </summary>
        internal static string msg_13 {
            get {
                return ResourceManager.GetString("msg_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择ATM编号和钞箱编号 的本地化字符串。
        /// </summary>
        internal static string msg_14 {
            get {
                return ResourceManager.GetString("msg_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写业务流水号 的本地化字符串。
        /// </summary>
        internal static string msg_15 {
            get {
                return ResourceManager.GetString("msg_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日志窗体异常！ 的本地化字符串。
        /// </summary>
        internal static string msg_16 {
            get {
                return ResourceManager.GetString("msg_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他厂家接入文件夹路径不存在！ 的本地化字符串。
        /// </summary>
        internal static string msg_17 {
            get {
                return ResourceManager.GetString("msg_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH导出路径不存在！ 的本地化字符串。
        /// </summary>
        internal static string msg_18 {
            get {
                return ResourceManager.GetString("msg_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功！是否打开导出目录？ 的本地化字符串。
        /// </summary>
        internal static string msg_19 {
            get {
                return ResourceManager.GetString("msg_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动监听异常！ 的本地化字符串。
        /// </summary>
        internal static string msg_2 {
            get {
                return ResourceManager.GetString("msg_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 秒后将自动关闭 的本地化字符串。
        /// </summary>
        internal static string msg_20 {
            get {
                return ResourceManager.GetString("msg_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请设置端口号 的本地化字符串。
        /// </summary>
        internal static string msg_21 {
            get {
                return ResourceManager.GetString("msg_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服务器连接成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_22 {
            get {
                return ResourceManager.GetString("msg_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服务器连接失败！ 的本地化字符串。
        /// </summary>
        internal static string msg_23 {
            get {
                return ResourceManager.GetString("msg_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像服务器连接成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_24 {
            get {
                return ResourceManager.GetString("msg_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像服务器连接失败！ 的本地化字符串。
        /// </summary>
        internal static string msg_25 {
            get {
                return ResourceManager.GetString("msg_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备服务器连接成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_26 {
            get {
                return ResourceManager.GetString("msg_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备服务器连接失败！ 的本地化字符串。
        /// </summary>
        internal static string msg_27 {
            get {
                return ResourceManager.GetString("msg_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据服务器连接成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_28 {
            get {
                return ResourceManager.GetString("msg_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据服务器连接失败！ 的本地化字符串。
        /// </summary>
        internal static string msg_29 {
            get {
                return ResourceManager.GetString("msg_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接‘推送服务器’，请查看‘服务器设置’是否正确？ 的本地化字符串。
        /// </summary>
        internal static string msg_3 {
            get {
                return ResourceManager.GetString("msg_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定成功！ 的本地化字符串。
        /// </summary>
        internal static string msg_30 {
            get {
                return ResourceManager.GetString("msg_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定失败！ 的本地化字符串。
        /// </summary>
        internal static string msg_31 {
            get {
                return ResourceManager.GetString("msg_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 已经绑定了IP：{1} 的本地化字符串。
        /// </summary>
        internal static string msg_32 {
            get {
                return ResourceManager.GetString("msg_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否继续？ 的本地化字符串。
        /// </summary>
        internal static string msg_33 {
            get {
                return ResourceManager.GetString("msg_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接‘数据服务器’，请查看‘服务器设置’是否正确？ 的本地化字符串。
        /// </summary>
        internal static string msg_4 {
            get {
                return ResourceManager.GetString("msg_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接‘图像数据库’，请查看‘服务器设置’是否正确？ 的本地化字符串。
        /// </summary>
        internal static string msg_5 {
            get {
                return ResourceManager.GetString("msg_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器还未配置，请在菜单下选择‘服务器设置’进行配置！ 的本地化字符串。
        /// </summary>
        internal static string msg_6 {
            get {
                return ResourceManager.GetString("msg_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误,请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string msg_7 {
            get {
                return ResourceManager.GetString("msg_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在！ 的本地化字符串。
        /// </summary>
        internal static string msg_8 {
            get {
                return ResourceManager.GetString("msg_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接设备数据库！ 的本地化字符串。
        /// </summary>
        internal static string msg_9 {
            get {
                return ResourceManager.GetString("msg_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string msg_Tip {
            get {
                return ResourceManager.GetString("msg_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        internal static string msg_Warn {
            get {
                return ResourceManager.GetString("msg_Warn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSN文件 的本地化字符串。
        /// </summary>
        internal static string rad_FSN {
            get {
                return ResourceManager.GetString("rad_FSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GZH文件 的本地化字符串。
        /// </summary>
        internal static string rad_GZH {
            get {
                return ResourceManager.GetString("rad_GZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        internal static string rb_CRHToday {
            get {
                return ResourceManager.GetString("rb_CRHToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昨天 的本地化字符串。
        /// </summary>
        internal static string rb_CRHYesterday {
            get {
                return ResourceManager.GetString("rb_CRHYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败！ 的本地化字符串。
        /// </summary>
        internal static string str_ImportFail {
            get {
                return ResourceManager.GetString("str_ImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功！ 的本地化字符串。
        /// </summary>
        internal static string str_ImportSuccess {
            get {
                return ResourceManager.GetString("str_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务日志 的本地化字符串。
        /// </summary>
        internal static string tab_Bussiness {
            get {
                return ResourceManager.GetString("tab_Bussiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令日志 的本地化字符串。
        /// </summary>
        internal static string tab_Cmd {
            get {
                return ResourceManager.GetString("tab_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH导出 的本地化字符串。
        /// </summary>
        internal static string tab_CRHExport {
            get {
                return ResourceManager.GetString("tab_CRHExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备监控 的本地化字符串。
        /// </summary>
        internal static string tab_DeviceControl {
            get {
                return ResourceManager.GetString("tab_DeviceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件上传 的本地化字符串。
        /// </summary>
        internal static string tab_FileUpload {
            get {
                return ResourceManager.GetString("tab_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSN导入日志 的本地化字符串。
        /// </summary>
        internal static string tab_FsnImport {
            get {
                return ResourceManager.GetString("tab_FsnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 他厂接入 的本地化字符串。
        /// </summary>
        internal static string tab_OtherFactoryAccess {
            get {
                return ResourceManager.GetString("tab_OtherFactoryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        internal static string tab_UserLogin {
            get {
                return ResourceManager.GetString("tab_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异步接收命令异常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_1 {
            get {
                return ResourceManager.GetString("TCPLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，传输数据结束命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_10 {
            get {
                return ResourceManager.GetString("TCPLog_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，时间同步命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_11 {
            get {
                return ResourceManager.GetString("TCPLog_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，心跳命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_12 {
            get {
                return ResourceManager.GetString("TCPLog_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，文件大小 {1} 字节,文件大小超过5M,将关闭连接！ {2} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_13 {
            get {
                return ResourceManager.GetString("TCPLog_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 达到最大连接数30的限制！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_14 {
            get {
                return ResourceManager.GetString("TCPLog_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，一次请求文件数超过30个，将关闭连接！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_15 {
            get {
                return ResourceManager.GetString("TCPLog_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}关闭线程！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_16 {
            get {
                return ResourceManager.GetString("TCPLog_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录Amount日志异常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_17 {
            get {
                return ResourceManager.GetString("TCPLog_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录命令日志异常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_18 {
            get {
                return ResourceManager.GetString("TCPLog_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录业务日志异常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_19 {
            get {
                return ResourceManager.GetString("TCPLog_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异步发送命令异常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_2 {
            get {
                return ResourceManager.GetString("TCPLog_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录FSN日志异常！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_20 {
            get {
                return ResourceManager.GetString("TCPLog_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，假币预警版本请求命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_21 {
            get {
                return ResourceManager.GetString("TCPLog_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，假币预警下载请求命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_22 {
            get {
                return ResourceManager.GetString("TCPLog_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，假币预警下载完成请求命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_23 {
            get {
                return ResourceManager.GetString("TCPLog_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令长度 {0} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_3 {
            get {
                return ResourceManager.GetString("TCPLog_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新连接 {0} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_4 {
            get {
                return ResourceManager.GetString("TCPLog_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}  IP地址未知,请确认已添加IP地址，再重启客户端或等待5分钟自动更新！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_5 {
            get {
                return ResourceManager.GetString("TCPLog_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 连接已存在！ 的本地化字符串。
        /// </summary>
        internal static string TCPLog_6 {
            get {
                return ResourceManager.GetString("TCPLog_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 未知命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_7 {
            get {
                return ResourceManager.GetString("TCPLog_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，传输数据请求命令 {1} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_8 {
            get {
                return ResourceManager.GetString("TCPLog_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}，纸币信息发送命令 数据包长度 {1}  纸币张数 {2} {3} 的本地化字符串。
        /// </summary>
        internal static string TCPLog_9 {
            get {
                return ResourceManager.GetString("TCPLog_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前总共 {0} 条收数据线程！ 的本地化字符串。
        /// </summary>
        internal static string TestLog_1 {
            get {
                return ResourceManager.GetString("TestLog_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在导出CRH... 的本地化字符串。
        /// </summary>
        internal static string wf_CRHExport {
            get {
                return ResourceManager.GetString("wf_CRHExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在初始化... 的本地化字符串。
        /// </summary>
        internal static string wf_Init {
            get {
                return ResourceManager.GetString("wf_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在载入数据... 的本地化字符串。
        /// </summary>
        internal static string wf_LoadData {
            get {
                return ResourceManager.GetString("wf_LoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在登录... 的本地化字符串。
        /// </summary>
        internal static string wf_Login {
            get {
                return ResourceManager.GetString("wf_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存文件... 的本地化字符串。
        /// </summary>
        internal static string wf_SaveFile {
            get {
                return ResourceManager.GetString("wf_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动监听... 的本地化字符串。
        /// </summary>
        internal static string wf_StartListen {
            get {
                return ResourceManager.GetString("wf_StartListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动推送... 的本地化字符串。
        /// </summary>
        internal static string wf_StartPush {
            get {
                return ResourceManager.GetString("wf_StartPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止监听... 的本地化字符串。
        /// </summary>
        internal static string wf_StopListen {
            get {
                return ResourceManager.GetString("wf_StopListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止推送... 的本地化字符串。
        /// </summary>
        internal static string wf_StopPush {
            get {
                return ResourceManager.GetString("wf_StopPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在测试设备服务器... 的本地化字符串。
        /// </summary>
        internal static string wf_TestDevice {
            get {
                return ResourceManager.GetString("wf_TestDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在测试图像服务器... 的本地化字符串。
        /// </summary>
        internal static string wf_TestPicture {
            get {
                return ResourceManager.GetString("wf_TestPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在测试推送服务器... 的本地化字符串。
        /// </summary>
        internal static string wf_TestPush {
            get {
                return ResourceManager.GetString("wf_TestPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在测试数据服务器... 的本地化字符串。
        /// </summary>
        internal static string wf_TestServer {
            get {
                return ResourceManager.GetString("wf_TestServer", resourceCulture);
            }
        }
    }
}
