//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KangYiCollection {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_zh_CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KangYiCollection.Resource.zh_CN", typeof(Resource_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string btn_Confirm {
            get {
                return ResourceManager.GetString("btn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动导出 的本地化字符串。
        /// </summary>
        internal static string btn_CRHManual {
            get {
                return ResourceManager.GetString("btn_CRHManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件 的本地化字符串。
        /// </summary>
        internal static string btn_CRHOpenFile {
            get {
                return ResourceManager.GetString("btn_CRHOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浏览 的本地化字符串。
        /// </summary>
        internal static string btn_Look {
            get {
                return ResourceManager.GetString("btn_Look", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择文件 的本地化字符串。
        /// </summary>
        internal static string btn_Scan {
            get {
                return ResourceManager.GetString("btn_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送绑定网点id：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_1 {
            get {
                return ResourceManager.GetString("buss_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务流水号是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_10 {
            get {
                return ResourceManager.GetString("buss_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATM的id是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_11 {
            get {
                return ResourceManager.GetString("buss_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钞箱编号的id是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_12 {
            get {
                return ResourceManager.GetString("buss_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否为清分中心：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_13 {
            get {
                return ResourceManager.GetString("buss_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包号是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_14 {
            get {
                return ResourceManager.GetString("buss_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捆钞序号是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_15 {
            get {
                return ResourceManager.GetString("buss_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已关闭浏览器,用户选择的机具id是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_16 {
            get {
                return ResourceManager.GetString("buss_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您绑定的网点id是：{0} 已被IP地址是：{1} 绑定了,一分钟后将尝试重连！ 的本地化字符串。
        /// </summary>
        internal static string buss_17 {
            get {
                return ResourceManager.GetString("buss_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试重连，已等待 {0} 次。 的本地化字符串。
        /// </summary>
        internal static string buss_18 {
            get {
                return ResourceManager.GetString("buss_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已断开到推送服务的连接！ 的本地化字符串。
        /// </summary>
        internal static string buss_19 {
            get {
                return ResourceManager.GetString("buss_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到开始命令，机具id是：{0} ，业务类型是：{1}，用户id是：{2} 的本地化字符串。
        /// </summary>
        internal static string buss_2 {
            get {
                return ResourceManager.GetString("buss_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该客户端未绑定网点，请先绑定网点！ 的本地化字符串。
        /// </summary>
        internal static string buss_20 {
            get {
                return ResourceManager.GetString("buss_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服务器异常！ 的本地化字符串。
        /// </summary>
        internal static string buss_21 {
            get {
                return ResourceManager.GetString("buss_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器上次连接时间：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_3 {
            get {
                return ResourceManager.GetString("buss_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一批张数是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_4 {
            get {
                return ResourceManager.GetString("buss_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析业务类型为：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_5 {
            get {
                return ResourceManager.GetString("buss_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机具id是：{0} 已失去连接。 的本地化字符串。
        /// </summary>
        internal static string buss_6 {
            get {
                return ResourceManager.GetString("buss_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机器上次连接时间： {0} 大于当前时间5分钟，视为未连接。 的本地化字符串。
        /// </summary>
        internal static string buss_7 {
            get {
                return ResourceManager.GetString("buss_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到结束命令,机具id是：{0} 的本地化字符串。
        /// </summary>
        internal static string buss_8 {
            get {
                return ResourceManager.GetString("buss_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收到撤销命令 的本地化字符串。
        /// </summary>
        internal static string buss_9 {
            get {
                return ResourceManager.GetString("buss_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用自动导出 的本地化字符串。
        /// </summary>
        internal static string chk_CRHExport {
            get {
                return ResourceManager.GetString("chk_CRHExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将指定文件夹下的FSN文件导入系统 的本地化字符串。
        /// </summary>
        internal static string chk_FactoryAccess {
            get {
                return ResourceManager.GetString("chk_FactoryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 号码记录,柜面取款,柜面存款,ATM配钞,ATM清钞 的本地化字符串。
        /// </summary>
        internal static string cmb_BusinessType {
            get {
                return ResourceManager.GetString("cmb_BusinessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录日期 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_0 {
            get {
                return ResourceManager.GetString("CRHCommon_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报送银行编码 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_1 {
            get {
                return ResourceManager.GetString("CRHCommon_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务关联信息 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_10 {
            get {
                return ResourceManager.GetString("CRHCommon_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成网点编码 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_2 {
            get {
                return ResourceManager.GetString("CRHCommon_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务类型 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_3 {
            get {
                return ResourceManager.GetString("CRHCommon_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录数 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_4 {
            get {
                return ResourceManager.GetString("CRHCommon_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现金清分中心 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_5 {
            get {
                return ResourceManager.GetString("CRHCommon_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件版本 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_6 {
            get {
                return ResourceManager.GetString("CRHCommon_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备类别 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_7 {
            get {
                return ResourceManager.GetString("CRHCommon_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机型 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_8 {
            get {
                return ResourceManager.GetString("CRHCommon_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备编号 的本地化字符串。
        /// </summary>
        internal static string CRHCommon_9 {
            get {
                return ResourceManager.GetString("CRHCommon_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_number {
            get {
                return ResourceManager.GetString("CRHRecord_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冠字号码 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordsign {
            get {
                return ResourceManager.GetString("CRHRecord_recordsign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录时间 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordtime {
            get {
                return ResourceManager.GetString("CRHRecord_recordtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 币值 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordvalue {
            get {
                return ResourceManager.GetString("CRHRecord_recordvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版别 的本地化字符串。
        /// </summary>
        internal static string CRHRecord_recordversion {
            get {
                return ResourceManager.GetString("CRHRecord_recordversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH查看 的本地化字符串。
        /// </summary>
        internal static string CRHReview {
            get {
                return ResourceManager.GetString("CRHReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定网点 的本地化字符串。
        /// </summary>
        internal static string gb_BindNode {
            get {
                return ResourceManager.GetString("gb_BindNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能设置 的本地化字符串。
        /// </summary>
        internal static string gb_CRH1 {
            get {
                return ResourceManager.GetString("gb_CRH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据时间范围设置 的本地化字符串。
        /// </summary>
        internal static string gb_CRH2 {
            get {
                return ResourceManager.GetString("gb_CRH2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动导出路径设置 的本地化字符串。
        /// </summary>
        internal static string gb_CRH3 {
            get {
                return ResourceManager.GetString("gb_CRH3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字段 的本地化字符串。
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备IP 的本地化字符串。
        /// </summary>
        internal static string kIpAddress {
            get {
                return ResourceManager.GetString("kIpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string kStatus {
            get {
                return ResourceManager.GetString("kStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近上传时间 的本地化字符串。
        /// </summary>
        internal static string kUpdateTime {
            get {
                return ResourceManager.GetString("kUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ATM编号 的本地化字符串。
        /// </summary>
        internal static string lab_ATM {
            get {
                return ResourceManager.GetString("lab_ATM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务流水号 的本地化字符串。
        /// </summary>
        internal static string lab_BussinessNumber {
            get {
                return ResourceManager.GetString("lab_BussinessNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钞箱编号 的本地化字符串。
        /// </summary>
        internal static string lab_CashBox {
            get {
                return ResourceManager.GetString("lab_CashBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公共信息部分： 的本地化字符串。
        /// </summary>
        internal static string lab_CRHCommon {
            get {
                return ResourceManager.GetString("lab_CRHCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冠字号码记录部分： 的本地化字符串。
        /// </summary>
        internal static string lab_CRHRecord {
            get {
                return ResourceManager.GetString("lab_CRHRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易类型 的本地化字符串。
        /// </summary>
        internal static string lab_DealType {
            get {
                return ResourceManager.GetString("lab_DealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备服务器IP 的本地化字符串。
        /// </summary>
        internal static string lab_DeviceIp {
            get {
                return ResourceManager.GetString("lab_DeviceIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹： 的本地化字符串。
        /// </summary>
        internal static string lab_Directory {
            get {
                return ResourceManager.GetString("lab_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属厂家 的本地化字符串。
        /// </summary>
        internal static string lab_Factory {
            get {
                return ResourceManager.GetString("lab_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本机IP 的本地化字符串。
        /// </summary>
        internal static string lab_LocalIp {
            get {
                return ResourceManager.GetString("lab_LocalIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属网点 的本地化字符串。
        /// </summary>
        internal static string lab_Node {
            get {
                return ResourceManager.GetString("lab_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开主目录 的本地化字符串。
        /// </summary>
        internal static string lab_OpenMainDir {
            get {
                return ResourceManager.GetString("lab_OpenMainDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string lab_Password {
            get {
                return ResourceManager.GetString("lab_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像数据库IP 的本地化字符串。
        /// </summary>
        internal static string lab_PictureIp {
            get {
                return ResourceManager.GetString("lab_PictureIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string lab_Port {
            get {
                return ResourceManager.GetString("lab_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推送服务器IP 的本地化字符串。
        /// </summary>
        internal static string lab_PushIp {
            get {
                return ResourceManager.GetString("lab_PushIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据服务器IP 的本地化字符串。
        /// </summary>
        internal static string lab_ServerIp {
            get {
                return ResourceManager.GetString("lab_ServerIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string lab_Test {
            get {
                return ResourceManager.GetString("lab_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传提示： 的本地化字符串。
        /// </summary>
        internal static string lab_UploadTip {
            get {
                return ResourceManager.GetString("lab_UploadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        internal static string lab_User {
            get {
                return ResourceManager.GetString("lab_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本：1.1.0.1 的本地化字符串。
        /// </summary>
        internal static string lab_Version {
            get {
                return ResourceManager.GetString("lab_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 路径不存在！ 的本地化字符串。
        /// </summary>
        internal static string log_1 {
            get {
                return ResourceManager.GetString("log_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH导出未启用！ 的本地化字符串。
        /// </summary>
        internal static string log_2 {
            get {
                return ResourceManager.GetString("log_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前队列还有{0}条执行语句... 的本地化字符串。
        /// </summary>
        internal static string log_3 {
            get {
                return ResourceManager.GetString("log_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前队列还有{0}个图像文件等待上传... 的本地化字符串。
        /// </summary>
        internal static string log_4 {
            get {
                return ResourceManager.GetString("log_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 图像文件上传失败,将添加到队列末尾 的本地化字符串。
        /// </summary>
        internal static string log_5 {
            get {
                return ResourceManager.GetString("log_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH查看 的本地化字符串。
        /// </summary>
        internal static string MenuItem_CRHReview {
            get {
                return ResourceManager.GetString("MenuItem_CRHReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能设置 的本地化字符串。
        /// </summary>
        internal static string MenuItem_FunctionSetting {
            get {
                return ResourceManager.GetString("MenuItem_FunctionSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        internal static string MenuItem_Log {
            get {
                return ResourceManager.GetString("MenuItem_Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string MenuItem_LogOut {
            get {
                return ResourceManager.GetString("MenuItem_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器设置 的本地化字符串。
        /// </summary>
        internal static string MenuItem_ServerSetting {
            get {
                return ResourceManager.GetString("MenuItem_ServerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接‘设备服务器’，请查看‘服务器设置’是否正确？ 的本地化字符串。
        /// </summary>
        internal static string msg_1 {
            get {
                return ResourceManager.GetString("msg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出软件后将无法接收纸币数据，是否退出软件？ 的本地化字符串。
        /// </summary>
        internal static string msg_10 {
            get {
                return ResourceManager.GetString("msg_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择文件所属厂家 的本地化字符串。
        /// </summary>
        internal static string msg_11 {
            get {
                return ResourceManager.GetString("msg_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择所属网点 的本地化字符串。
        /// </summary>
        internal static string msg_12 {
            get {
                return ResourceManager.GetString("msg_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择交易类型 的本地化字符串。
        /// </summary>
        internal static string msg_13 {
            get {
                return ResourceManager.GetString("msg_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择ATM编号和钞箱编号 的本地化字符串。
        /// </summary>
        internal static string msg_14 {
            get {
                return ResourceManager.GetString("msg_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写业务流水号 的本地化字符串。
        /// </summary>
        internal static string msg_15 {
            get {
                return ResourceManager.GetString("msg_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开日志窗体异常！ 的本地化字符串。
        /// </summary>
        internal static string msg_16 {
            get {
                return ResourceManager.GetString("msg_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动监听异常！ 的本地化字符串。
        /// </summary>
        internal static string msg_2 {
            get {
                return ResourceManager.GetString("msg_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接‘推送服务器’，请查看‘服务器设置’是否正确？ 的本地化字符串。
        /// </summary>
        internal static string msg_3 {
            get {
                return ResourceManager.GetString("msg_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接‘数据服务器’，请查看‘服务器设置’是否正确？ 的本地化字符串。
        /// </summary>
        internal static string msg_4 {
            get {
                return ResourceManager.GetString("msg_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接‘图像数据库’，请查看‘服务器设置’是否正确？ 的本地化字符串。
        /// </summary>
        internal static string msg_5 {
            get {
                return ResourceManager.GetString("msg_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器还未配置，请在菜单下选择‘服务器设置’进行配置！ 的本地化字符串。
        /// </summary>
        internal static string msg_6 {
            get {
                return ResourceManager.GetString("msg_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码错误,请重新输入！ 的本地化字符串。
        /// </summary>
        internal static string msg_7 {
            get {
                return ResourceManager.GetString("msg_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在！ 的本地化字符串。
        /// </summary>
        internal static string msg_8 {
            get {
                return ResourceManager.GetString("msg_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法连接设备数据库！ 的本地化字符串。
        /// </summary>
        internal static string msg_9 {
            get {
                return ResourceManager.GetString("msg_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string msg_Tip {
            get {
                return ResourceManager.GetString("msg_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSN文件 的本地化字符串。
        /// </summary>
        internal static string rad_FSN {
            get {
                return ResourceManager.GetString("rad_FSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GZH文件 的本地化字符串。
        /// </summary>
        internal static string rad_GZH {
            get {
                return ResourceManager.GetString("rad_GZH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        internal static string rb_CRHToday {
            get {
                return ResourceManager.GetString("rb_CRHToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昨天 的本地化字符串。
        /// </summary>
        internal static string rb_CRHYesterday {
            get {
                return ResourceManager.GetString("rb_CRHYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败 的本地化字符串。
        /// </summary>
        internal static string str_ImportFail {
            get {
                return ResourceManager.GetString("str_ImportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功 的本地化字符串。
        /// </summary>
        internal static string str_ImportSuccess {
            get {
                return ResourceManager.GetString("str_ImportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 业务日志 的本地化字符串。
        /// </summary>
        internal static string tab_Bussiness {
            get {
                return ResourceManager.GetString("tab_Bussiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令日志 的本地化字符串。
        /// </summary>
        internal static string tab_Cmd {
            get {
                return ResourceManager.GetString("tab_Cmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CRH导出 的本地化字符串。
        /// </summary>
        internal static string tab_CRHExport {
            get {
                return ResourceManager.GetString("tab_CRHExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备监控 的本地化字符串。
        /// </summary>
        internal static string tab_DeviceControl {
            get {
                return ResourceManager.GetString("tab_DeviceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件上传 的本地化字符串。
        /// </summary>
        internal static string tab_FileUpload {
            get {
                return ResourceManager.GetString("tab_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FSN导入日志 的本地化字符串。
        /// </summary>
        internal static string tab_FsnImport {
            get {
                return ResourceManager.GetString("tab_FsnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 他厂接入 的本地化字符串。
        /// </summary>
        internal static string tab_OtherFactoryAccess {
            get {
                return ResourceManager.GetString("tab_OtherFactoryAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        internal static string tab_UserLogin {
            get {
                return ResourceManager.GetString("tab_UserLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在登录... 的本地化字符串。
        /// </summary>
        internal static string wf_Login {
            get {
                return ResourceManager.GetString("wf_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存文件... 的本地化字符串。
        /// </summary>
        internal static string wf_SaveFile {
            get {
                return ResourceManager.GetString("wf_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动监听... 的本地化字符串。
        /// </summary>
        internal static string wf_StartListen {
            get {
                return ResourceManager.GetString("wf_StartListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在启动推送... 的本地化字符串。
        /// </summary>
        internal static string wf_StartPush {
            get {
                return ResourceManager.GetString("wf_StartPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止监听... 的本地化字符串。
        /// </summary>
        internal static string wf_StopListen {
            get {
                return ResourceManager.GetString("wf_StopListen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在停止推送... 的本地化字符串。
        /// </summary>
        internal static string wf_StopPush {
            get {
                return ResourceManager.GetString("wf_StopPush", resourceCulture);
            }
        }
    }
}
